# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f35b620fd62abf8a9178c599f215eb0d768ff550a1aab685c0369626e01ad904587953ffb627c87df57a99c5540aad8d99df3ad838cbf9160baef1abd0d46f7

test:
  secret_key_base: 2abac714acde6fc4723c107ffd9017d5df705445f5d30adc34c20e165aa4b41d1de3b017e473b780e8dce957cfea15fe9e15874c8ff88ed3f9c25c99b4bb559d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
